### ISSUE TITLE
As a OSCAL SSP validation developer, I would like build quality checks, so that I can use different metrics to evaluate the quality of my changes.

### ISSUE THREAD

**Issue by mike-stern** [18F/fedramp-automation#10] opened 2020-10-29 18:47 UTC
Add code quality into the pipeline:

- [ ] need performance on canonical examples to baseline performance and impact of changes (Saxon)?
- [ ] xpec allows for coverage checks
- [ ] xpec allows for other quality checks
- [ ] linters for shell scripts
- [ ] linter for xsl?

**Comment by sstatz** [comment] 2021-07-20 14:51
Duplicate of #73

**Closed by sstatz** 2021-07-20 14:51 UTC
Labels: enhancement, story
